steps:
  # Passo 1: Build da Imagem Docker (sem alterações)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag/image:latest', '.']
    id: Build

  # Passo 2: Push da Imagem para o Artifact Registry (sem alterações)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag/image:latest']
    id: Push
    waitFor: ['Build']

  # --- PASSO 3: Deploy no Cloud Run (MODIFICADO PARA OPÇÃO 2 - IP PÚBLICO) ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chat-rag' # <-- Nome do seu serviço Cloud Run
      - '--image'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag/image:latest' # <-- Imagem do passo anterior
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-east4' # <-- Sua Região
      # --- Variáveis de Ambiente para IP Público ---
      - '--set-env-vars=PG_DB=postgres,PG_USER=postgres,PG_PASSWORD=AMGQk@50l9Eu,DB_PUBLIC_IP=34.48.95.143'
        # !!! ALERTA DE SEGURANÇA: Senha no código! Use Secret Manager (veja abaixo) !!!
      - '--allow-unauthenticated'
      # --- Configuração de Rede para Saída Pública ---
      - '--vpc-egress=all' # <-- PERMITE SAÍDA PARA INTERNET PÚBLICA
      # --- Conta de Serviço (mantida) ---
      - '--service-account=682048092511-compute@developer.gserviceaccount.com'
      # --- FLAGS REMOVIDAS (Não usadas na Opção 2) ---
      # REMOVIDO: --add-cloudsql-instances
      # REMOVIDO: --vpc-connector
    waitFor: ['Push'] # Espera o passo 'Push' terminar

options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag/image:latest'