# cloudbuild.yaml - Configurado para chat-rag-v2 (Opção 2: IP Público)
# Build executado na região 'global' com cache de camadas Docker habilitado.
# Deploy feito em 'us-east4'.

steps:
  # Passo 1: Build da Imagem Docker (com Cache Habilitado)
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      # --- Habilita Cache ---
      # Usa a imagem 'latest' anterior como cache.
      # O primeiro build será lento, os subsequentes serão mais rápidos
      # se as dependências não mudarem.
      - '--cache-from'
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag-repo-v2/image:latest'
      # --------------------
      - '-t'
      # Tag da imagem a ser construída (destino no repo us-east4)
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag-repo-v2/image:latest'
      - '.' # Diretório de contexto (onde o Dockerfile está)

  # Passo 2: Push da Imagem para o Artifact Registry (em us-east4)
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      # Destino do push no repo em us-east4
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag-repo-v2/image:latest'
    waitFor: ['Build'] # Espera o passo 'Build' terminar

  # --- PASSO 3: Deploy no Cloud Run (Configurado para OPÇÃO 2 - IP PÚBLICO) ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      # Nome do serviço Cloud Run
      - 'chat-rag-v2'
      - '--image'
      # Imagem do passo anterior (do repo us-east4)
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag-repo-v2/image:latest'
      - '--platform'
      - 'managed'
      # Região do Deploy
      - '--region'
      - 'us-east4'
      # Variáveis de Ambiente para IP Público
      - '--set-env-vars=PG_DB=postgres,PG_USER=llamaindex,PG_PASSWORD=password123,DB_PUBLIC_IP=34.150.190.157,PG_PORT=5432'
      # Referência ao Secret Manager para a API key do OpenAI
      - '--set-secrets=OPENAI_API_KEY=openai-api-key:latest'
      - '--allow-unauthenticated'
      # Sem flags de VPC/Egress, permitindo saída padrão para internet
      # Conta de Serviço
      - '--service-account=${_SERVICE_ACCOUNT_EMAIL}'
    waitFor: ['Push'] # Espera o passo 'Push' terminar

# Configurações Globais do Build
options:
  logging: CLOUD_LOGGING_ONLY
  # O build executa na pool global por padrão (sem 'region:' aqui)

# Imagens resultantes do build (opcional)
images:
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag-repo-v2/image:latest'

# Substituições
substitutions:
  # Define a conta de serviço do Cloud Run a ser usada (Padrão do Compute Engine)
  _SERVICE_ACCOUNT_EMAIL: '${PROJECT_NUMBER}-compute@developer.gserviceaccount.com'
  # Adicione outras substituições se necessário
  # _REGION: 'us-east4'

# Nota: É necessário criar o seguinte secret no Secret Manager:
# - openai-api-key: Contendo a chave de API do OpenAI