steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/chat-rag-v1/chat-rag/image:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/chat-rag-v1/chat-rag/image:latest']
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'us-east4-docker.pkg.dev/chat-rag-v1/chat-rag/image:latest'