# cloudbuild.yaml - Configurado para chat-rag-v2 (Opção 2: IP Público)
# Build executado na região 'global' para evitar quotas regionais.

steps:
  # Passo 1: Build da Imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      # O destino da imagem continua sendo o repo em us-east4
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag-repo-v2/image:latest'
      - '.'
    id: Build

  # Passo 2: Push da Imagem para o Artifact Registry (em us-east4)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      # O destino do push continua sendo o repo em us-east4
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag-repo-v2/image:latest'
    id: Push
    waitFor: ['Build'] # Espera o passo 'Build' terminar

  # --- PASSO 3: Deploy no Cloud Run (ainda para us-east4) ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      # Nome do serviço Cloud Run
      - 'chat-rag-v2'
      - '--image'
      # Imagem do passo anterior (do repo us-east4)
      - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag-repo-v2/image:latest'
      - '--platform'
      - 'managed'
      # --- REGIÃO DO DEPLOY (Mantida como us-east4) ---
      - '--region'
      - 'us-east4'
      # --- Variáveis de Ambiente para IP Público ---
      - '--set-env-vars=PG_DB=postgres,PG_USER=postgres,PG_PASSWORD=SUA_SENHA_DEFINIDA_AQUI,DB_PUBLIC_IP=34.150.190.157'
        # !!! ALERTA DE SEGURANÇA: Substitua SUA_SENHA_DEFINIDA_AQUI pela senha real!
        # !!! RECOMENDADO: Use Secret Manager para a senha em produção!
      - '--allow-unauthenticated'
      # --- Configuração de Rede para Saída Pública ---
      - '--vpc-egress=all'
      # --- Conta de Serviço (Use a padrão do Compute Engine ou crie uma dedicada) ---
      - '--service-account=${_SERVICE_ACCOUNT_EMAIL}'
    waitFor: ['Push'] # Espera o passo 'Push' terminar

# Configurações Globais do Build
options:
  logging: CLOUD_LOGGING_ONLY
  # --- REGIÃO DE EXECUÇÃO DO BUILD (Alterado para global) ---
  region: 'global'

# Imagens resultantes do build (opcional)
images:
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/chat-rag-repo-v2/image:latest'

# Substituições
substitutions:
  # Define a conta de serviço do Cloud Run a ser usada (Padrão do Compute Engine)
  _SERVICE_ACCOUNT_EMAIL: '${PROJECT_NUMBER}-compute@developer.gserviceaccount.com'
  # Adicione a região aqui se quiser referenciá-la em outros lugares, mas o deploy a define explicitamente
  # _REGION: 'us-east4'

# (Seção availableSecrets para Secret Manager omitida para brevidade, adicione se usar)