steps:
  # Constrói a imagem do Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/chat-rag-v1/chat-rag', '.']
  
  # Push da imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/chat-rag-v1/chat-rag']

# Armazena logs no bucket que você criou
logsBucket: 'gs://chat-rag'

# Configuração de opções
options:
  logging: CLOUD_LOGGING_ONLY

# Define a imagem final que será usada
images:
  - 'gcr.io/chat-rag-v1/chat-rag'